version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M@sw9fes.kf
      - MSSQL_PID=Express
    volumes:
      - C:\sqldata:/var/opt/mssql/data
 
  eshopwebmvc:
    #image: eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
            - sql-server
    links: 
            - sql-server 
    

  eshoppublicapi:
   # image: eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
            - sql-server

  nginx:
    image: nginx:latest
    depends_on:
      - sql-server
    #volumes:
      #- C:\sqldata:/etc/nginx/conf.d/
    volumes:
      - C:\eShopOnWeb\Nginx conf\nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links: 
            - eshopwebmvc 
    