apiVersion: v1
kind: Namespace
metadata:
  name: apache
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
  namespace: apache
spec:
  type: NodePort
  selector:
    app: httpd_app_nautilus
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  namespace: apache
  labels:
    app: httpd_app_nautilus
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      containers:
        - name: httpd-container-nautilus
          image: dmytroslotvinskyy/eshoponweb:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: httpd_app_nautilus
data:
  # db-connection-string: Server=tcp:mssql-paas.database.windows.net,1433;Initial Catalog=ProductsDB;Persist Security Info=False;User ID=houssem;Password=@Aa123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
  CatalogConnection: Server=mssql-service;Integrated Security=false;User ID=sa;Password=M@sw9fes.kf;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;
  IdentityConnection: Server=mssql-service;Integrated Security=false;User ID=sa;Password=M@sw9fes.kf;Initial Catalog=Microsoft.eShopOnWeb.Identity;
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
     # terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
      # image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
      # image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        image: mcr.microsoft.com/mssql/server:2019-latest
      # image: microsoft/mssql-server-linux
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        -name: MSSQL_PID
          value: Express
        - name: SA_PASSWORD
          value: "M@sw9fes.kf"
        volumeMounts:
        - name: mysql-pv-claim
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mysql-pv-claim
           
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
spec:
  capacity:
    storage: 512Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mssql-local-storage
  local:
    path: /c/sqldata/

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30200
  type: NodePort
---