apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
  namespace: apache
  labels:
    type: local
    app: mssql-database
spec:
  capacity:
    storage: 512Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/db" # created this folder at C:\kubernetes-mount-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pv-claim
  namespace: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: apache
  labels:
    app: mssql-database
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain 
---